In [1]:
import numpy as np
import time

In [2]:
my_list = list(range(1_000_000))

In [3]:
start_time = time.time()
result_list = [x * 2 for x in my_list]
end_time = time.time()

In [5]:
print(f"파이썬 리스트 실행 시간: {end_time - start_time:.5f}초")

파이썬 리스트 실행 시간: 0.02946초


In [6]:
my_array = np.arange(1_000_000)
start_time = time.time()
result_array = my_array * 2
end_time = time.time()
print(f"넘파이 배열 실행 시간: {end_time - start_time:.5f}초")

넘파이 배열 실행 시간: 0.00179초


## NumPy 라이브러리

NumPy(Numerical Python)는 파이썬에서 수치 계산을 효율적으로 수행하기 위한 핵심 라이브러리입니다. 특히 다차원 배열(ndarray) 객체를 지원하며, 이 배열을 사용하여 빠르고 효율적인 수학 및 논리 연산을 수행할 수 있습니다.

**주요 특징:**

*   **빠른 계산 속도:** C로 구현되어 있어 파이썬 기본 리스트보다 훨씬 빠른 연산 속도를 자랑합니다.
*   **메모리 효율성:** 배열은 연속적인 메모리 공간에 저장되어 메모리 사용이 효율적입니다.
*   **다차원 배열 객체(ndarray):** 벡터, 행렬 등 다양한 형태의 데이터를 표현할 수 있습니다.
*   **다양한 수학 함수 제공:** 선형 대수, 푸리에 변환 등 다양한 수학 함수를 내장하고 있습니다.
*   **브로드캐스팅 기능:** 크기가 다른 배열 간의 연산을 쉽게 수행할 수 있도록 지원합니다.

**주요 사용 분야:**

*   데이터 분석 및 과학
*   머신러닝 및 딥러닝
*   과학 계산 및 시뮬레이션
*   이미지 및 신호 처리

NumPy는 파이썬 생태계에서 데이터 과학 및 수치 계산 분야의 필수 도구로 널리 사용되고 있습니다.

## `np.arange()` 메소드

`np.arange()`는 NumPy에서 지정된 범위 내에서 균일한 간격의 값을 갖는 배열을 생성하는 함수입니다. 파이썬의 내장 함수인 `range()`와 유사하지만, NumPy 배열을 반환한다는 차이가 있습니다.

**기본 문법:**

## NumPy 주요 메소드

NumPy는 배열을 다루기 위한 다양한 유용한 메소드를 제공합니다. 몇 가지 예시는 다음과 같습니다.

*   **`np.array()`**: 파이썬 리스트나 튜플을 NumPy 배열로 변환합니다.
*   **`.shape`**: 배열의 각 차원의 크기를 나타내는 튜플을 반환합니다.
*   `.dtype`: 배열 요소의 데이터 타입을 반환합니다.
*   **`.reshape()`**: 배열의 형태를 변경합니다.
*   **`.sum()`**: 배열 요소의 합을 계산합니다.
*   **`.mean()`**: 배열 요소의 평균을 계산합니다.
*   **`.max()`**: 배열 요소 중 최댓값을 찾습니다.
*   **`.min()`**: 배열 요소 중 최솟값을 찾습니다.
*   **`np.zeros()`**: 모든 요소가 0인 배열을 생성합니다.
*   **`np.ones()`**: 모든 요소가 1인 배열을 생성합니다.
*   **`np.arange()`**: 주어진 범위 내에서 균일한 간격의 값을 갖는 배열을 생성합니다.
*   **`np.linspace()`**: 주어진 범위 내에서 지정된 개수의 균일한 간격의 값을 갖는 배열을 생성합니다.

In [7]:
import numpy as np

# 0부터 10 미만까지 1씩 증가하는 배열 생성
arr1 = np.arange(10)
print("np.arange(10):", arr1)

# 2부터 10 미만까지 1씩 증가하는 배열 생성
arr2 = np.arange(2, 10)
print("np.arange(2, 10):", arr2)

# 2부터 10 미만까지 2씩 증가하는 배열 생성
arr3 = np.arange(2, 10, 2)
print("np.arange(2, 10, 2):", arr3)

# 0부터 1 미만까지 0.1씩 증가하는 배열 생성 (부동 소수점 step)
arr4 = np.arange(0, 1, 0.1)
print("np.arange(0, 1, 0.1):", arr4)

np.arange(10): [0 1 2 3 4 5 6 7 8 9]
np.arange(2, 10): [2 3 4 5 6 7 8 9]
np.arange(2, 10, 2): [2 4 6 8]
np.arange(0, 1, 0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [8]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
a = np.array([1, 2, 3, 4, 5])
# 배열의 모든 요소에 10 더하기
print(a + 10)
# 배열의 모든 요소에 2 곱하기
print(a * 2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [12]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
# 배열끼리 덧셈 (10+1, 20+2, 30+3)
print(arr1 + arr2)

[11 22 33]


In [13]:
print(np.sum(a))

15


In [14]:
a = np.array([10, 20, 30, 40, 50])

In [15]:
print(a[1:4])

[20 30 40]


In [16]:
a = np.array([10, 20, 30, 40, 50])
# 배열 a의 요소 중 25보다 큰 값만 선택
condition_mask = (a > 25) # 1단계: 불리언 마스크 생성
filtered_array = a[condition_mask] # 2단계: 마스크를 사용해 데이터 필터링
print(filtered_array)

[30 40 50]


In [17]:
# 1차원 배열
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
# 2차원 배열
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

(6,)
(2, 3)


In [19]:
# 6개의 요소를 가진 1차원 배열
arr1 = np.array([1, 2, 3, 4, 5, 6])
# arr1을 3행 2열의 2차원 배열로 변경
arr2 = arr1.reshape(3, 2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
import numpy as np
# 비행 거리 배열 (단위: km)
distances = np.array([1, 2, 3, 5, 8])
# 각 비행 시 예상 풍속 배열 (단위: m/s)
windspeeds = np.array([0, 5, 10, 7, 12])

In [21]:
# 기본 배터리 소모율 (단위: %/km)
base_usage_rate = 10
# 풍속에 따른 추가 소모율 (단위: %/km)
additional_usage_rate = windspeeds

In [22]:
# 각 시나리오의 최종 소모율 (%/km)
total_usage_rate = base_usage_rate + additional_usage_rate

In [23]:
# 최종 소모량 (%) = 거리(km) * 소모율(%/km)
battery_consumption = distances * total_usage_rate

In [24]:
print("비행 거리 (km):", distances)
print("풍속 (m/s):", windspeeds)
print("총 소모율 (%/km):", total_usage_rate)
print("예상 배터리 소모량 (%):", battery_consumption)

비행 거리 (km): [1 2 3 5 8]
풍속 (m/s): [ 0  5 10  7 12]
총 소모율 (%/km): [10 15 20 17 22]
예상 배터리 소모량 (%): [ 10  30  60  85 176]


In [25]:
import pandas as pd
student_data = {
'name': ['Kim', 'Lee', 'Park'],
'test': [85, 92, 78],
'assign1': [88, 95, 80],
'assign2': [91, 89, 82]
}
df = pd.DataFrame(student_data)
display(df)

name  test  assign1  assign2
0   Kim    85       88       91
1   Lee    92       95       89
2  Park    78       80       82

In [33]:
import pandas as pd

# 'Iris.csv' 파일 불러오기
try:
    df_csv = pd.read_csv('/content/Iris.csv')
    display(df_csv.head())
except FileNotFoundError:
    print("CSV 파일을 찾을 수 없습니다. 파일 경로를 확인해주세요.")
except Exception as e:
    print(f"파일을 불러오는 중 오류가 발생했습니다: {e}")

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [35]:
id_column = df_csv['Id']
print(id_column)

0        1
1        2
2        3
3        4
4        5
      ... 
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64


In [38]:
filtered_df = df_csv[df_csv['SepalLengthCm'] < 5]

display(filtered_df)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
6      7            4.6           3.4            1.4           0.3   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
22    23            4.6           3.6            1.0           0.2   
24    25            4.8           3.4            1.9           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
34    35            4.9           3.1            1.5           0.1   
37    38            4.9           3.1            1.5           0.1   
38    39            4.4           3.0            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
42    43            4.4           3.2            1.3           0.2   
45    46            4.8           3.0            1.4           0.3   
47    48            4.6           3.2            1.4           0.2   
57    58            4.9           2.4            3.3           1.0   
106  107            4.9           2.5            4.5           1.7   

             Species  
1        Iris-setosa  
2        Iris-setosa  
3        Iris-setosa  
6        Iris-setosa  
8        Iris-setosa  
9        Iris-setosa  
11       Iris-setosa  
12       Iris-setosa  
13       Iris-setosa  
22       Iris-setosa  
24       Iris-setosa  
29       Iris-setosa  
30       Iris-setosa  
34       Iris-setosa  
37       Iris-setosa  
38       Iris-setosa  
41       Iris-setosa  
42       Iris-setosa  
45       Iris-setosa  
47       Iris-setosa  
57   Iris-versicolor  
106   Iris-virginica